### ISSUE TITLE
ServiceScope - LanguageSet (serviceInteractionLanguage)

### ISSUE THREAD

**Issue by MiltosD** [ISD-Catalogue/ISD-catalogue#23]
Form not validation as expected. Added language, but did not validate. Thrown error.

**Comment by MiltosD** [comment]
This should possibly be resolved on the javascript level

**Comment by gkirtzou** [comment]
Issue solved at https://github.com/ISD-Catalogue/ISD-catalogue/commit/cfaf2ea3714c3b1d4e1df39e54a2af478b8cea33
