### ISSUE TITLE
service appears as both external and not external

### ISSUE THREAD

**Issue by MariaGiagkou** [ISD-Catalogue/ISD-catalogue#49]
Service "Translator of the Austrian Presidency of the Council of the EU" is documented as external. However it appears in both this list https://cef-at-service-catalogue.eu/catalogue/search/?q=service_ownership_status_filter_not_exact:External 
and in this list https://cef-at-service-catalogue.eu/catalogue/search/?q=&selected_facets=service_ownership_status_filter_exact:External

**Comment by gkirtzou** [comment]
Bug fixed at commit https://github.com/ISD-Catalogue/ISD-catalogue/tree/db4a85293f6f569278f72aecb0bbb6630365c847 and https://github.com/ISD-Catalogue/ISD-catalogue/tree/71d5f1b231f60fe6f5688d2c38b68a70154b7060

Patch uploaded to production
