### ISSUE TITLE
Cancel button

### ISSUE THREAD

**Issue by MariaGiagkou** [ISD-Catalogue/ISD-catalogue#50]
Add a cancel button on all Editor pages

**Comment by gkirtzou** [comment]
Features was implemented in commits https://github.com/ISD-Catalogue/ISD-catalogue/commit/a408ae400d6db7088dff4a482dcfece093ff1077 and https://github.com/ISD-Catalogue/ISD-catalogue/commit/0cf4ab9eac0debb92e6baebc474fb52e7b65dc04

Feature released both in development and production sites
